### ISSUE TITLE
CONV variant parallelized on output channel dimension

### ISSUE THREAD

**Issue by FrancescoConti** [pulp-platform/pulp-nn#2]
In some corner cases, it could be more advantageous to parallelize convolutions over the _Kout_ dimension instead of the _Hout/Wout remainder_ (like in depthwise conv's).
**Potential advantages**:
- better parallelism when Hout is small
- same reuse pattern

**Potential disadvantages**:
- could trigger more TCDM contention than Hout/Wout parallelization as cores share the same input.

@NBruschi @anga93 what do you think?

**Comment by NBruschi** [comment]
Added sources and headers of standard convolution and matmul kernels which are named pulp_nn_conv_Co_parallel and pulp_nn_matmul_Co_parallel respectively at the 8bit library.

**Comment by FrancescoConti** [comment]
Super-fast! I'll keep the issue open till we test it a bit in DORY...
